# Sample sqlsync.ini file

tables = *
# skip = sometable

[keys]
# primary = id
# timestamp = updated

[source]
uri = MariaDB://sqlsync@remotehost/somedb
pwd = secret

[target]
uri = MariaDB://sqlsync@localhost/targetdb
pwd = alsosecret
